services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Blueways\BwTodoSite\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Blueways\BwTodoSite\Mvc\View\JsonView:
    public: true
